name: Build Geode Mod
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Geode CLI v3.9.0
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/geode-sdk/cli/releases/download/v3.9.0/geode-windows.exe" -OutFile "geode.exe"

      - name: Install SDK
        run: .\geode.exe sdk install --version 3.9.0 --yes

      - name: Build mod
        run: .\geode.exe build

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/package/*.geode
